Repository Project-Sloth/ps-housing, pull requests merged in 2023-08, with the labels that each got.

#85 Fixes nil after deleting property
  server/sv_property.lua
Labels: needs testing

#82 Addind Sound when Entering/Leaving
  client/cl_property.lua
Labels: enhancement

#86 Optimizations + Stop murdering of server
  client/cl_property.lua
  client/client.lua
  client/modeler.lua
  server/server.lua
  shared/framework.lua
Labels: needs testing

#74 Fix Issue Taking Payment For Furniture
  server/sv_property.lua
Labels: needs testing

#98 Fixed Videos in Readme
  README.md
Labels: ready for merge

#90 Added Required Item (police_stormram) For Raid
  server/sv_property.lua
Labels: ready for merge

#96 Clothing Fix for QB & illenium
  server/server.lua
Labels: ready for merge

#91 Correct Trigger and Garagezone
  client/cl_property.lua
Labels: ready for merge

#94 Changing Images of House 3
  shared/config.lua
Labels: ready for merge

#97 Fix for Doors being Limited
  README.md
  html/index.js
  ui/src/components/ItemList.svelte
  ui/src/components/Modeler.svelte
Labels: ready for merge

#109 Furniture table element fix
  client/cl_property.lua
  server/sv_property.lua
Labels: needs testing

#89 Migrate houses/apartments from qb-houses/qb-apartments
  README.md
  client/migrate.lua
  fxmanifest.lua
  server/migrate.lua
Labels: needs testing

#123 updated stretched pics
  shared/config.lua
Labels: needs testing

#124 added ,,how to add new shells'' and removed To-Do
  README.md
Labels: ready for merge

#122 Fixing the incorrect table name in server.lua and updating the README with the solution for the properties.sql import issue.
  README.md
  server/server.lua
Labels: ready for merge
